"""
Configuraciones globales, listas de mapeo y constantes.
"""

MES_A_NOMBRE = {
    1: 'Enero', 2: 'Febrero', 3: 'Marzo', 4: 'Abril',
    5: 'Mayo', 6: 'Junio', 7: 'Julio', 8: 'Agosto',
    9: 'Septiembre', 10: 'Octubre', 11: 'Noviembre', 12: 'Diciembre'
}

PROFESION_LISTA = [
    "MÉDICO", "ESTUDIANTE", "PROFESIONAL", "OTRA", "UNIVERSIDAD", "ODONTÓLOGO", "PACIENTE", "PARAMÉDICO",
    "ENFERMERO(A)", "QUÍMICO FAR.", "DISTRIBUIDOR", "INVESTIGADOR", "FARMACÉUTICO", "REPRESENTANTE", 
    "MÉDICO VET.", "PSICÓLOGO", "TERAPEUTA", "INGENIERO Q.", "BIÓLOGO", "DUEÑO DE M.", "PERSONAL INI.",
    "TÉCNICO LAB.", "AGRÓNOMO", "ASOCIACIÓN", "INGENIERO EI", "DUEÑO DE CL", "QUÍMICO BIÓ", 
    "TÉCNICO RAD.", "FARMACIA VE", "DUEÑO DE FA", "PRODUCTOR", "NO ASIGNADO", "SIN ESPECIFIC", 
    "QUÍMICO FA.", "N/A", "PROFESIONAL DE LA SALUD"
]

AGRUPADOR_LISTA = [
    "MÉDICO", "OTRAS PROFESIONES", "PROFESIONAL DE LA SALUD", "OTRAS PROFESIONES", "OTRAS PROFESIONES", 
    "PROFESIONAL DE LA SALUD", "OTRAS PROFESIONES", "PROFESIONAL DE LA SALUD", "PROFESIONAL DE LA SALUD", 
    "PROFESIONAL DE LA SALUD", "OTRAS PROFESIONES", "OTRAS PROFESIONES", "PROFESIONAL DE LA SALUD", 
    "OTRAS PROFESIONES", "OTRAS PROFESIONES", "OTRAS PROFESIONES", "PROFESIONAL DE LA SALUD", 
    "OTRAS PROFESIONES", "OTRAS PROFESIONES", "OTRAS PROFESIONES", "OTRAS PROFESIONES", 
    "PROFESIONAL DE LA SALUD", "OTRAS PROFESIONES", "OTRAS PROFESIONES", "OTRAS PROFESIONES", 
    "OTRAS PROFESIONES", "PROFESIONAL DE LA SALUD", "OTRAS PROFESIONES", "OTRAS PROFESIONES", 
    "OTRAS PROFESIONES", "OTRAS PROFESIONES", "NO ESPECIFICADA", "NO ESPECIFICADA", "NO ESPECIFICADA", 
    "NO ESPECIFICADA", "PROFESIONAL DE LA SALUD"
]

# Normalizar longitudes e inicializar mapeo
max_len = max(len(PROFESION_LISTA), len(AGRUPADOR_LISTA))
PROFESION_LISTA += ["NO ESPECIFICADA"] * (max_len - len(PROFESION_LISTA))
AGRUPADOR_LISTA += ["NO ESPECIFICADA"] * (max_len - len(AGRUPADOR_LISTA))

MAPEO_PROFESIONES = dict(zip(PROFESION_LISTA, AGRUPADOR_LISTA))

ESPECIALIDADES_MEDICAS = [
    "ALERGOLOGÍA", "ALGOLOGÍA", "ANÁLISIS CLÍNICOS", "ANATOMÍA PATOLÓGICA", "ANDROLOGÍA", 
    "ANESTESIOLOGÍA", "ANGIOLOGÍA", "AUDIOLOGÍA, OTONEUROLOGÍA Y FONIATRÍA", "BACTERIOLOGÍA", 
    "VIROLOGÍA", "BARIATRÍA", "CALIDAD DE LA ATENCIÓN CLÍNICA", "CARDIOLOGÍA", "CIRUGÍA", 
    "CIRUGÍA ONCOLÓGICA", "CIRUGÍA PEDIÁTRICA", "CIRUGÍA PLÁSTICA", "COLOPROCTOLOGÍA", 
    "DERMATOLOGÍA", "DIABETOLOGÍA", "ECOGRAFÍA", "ENDOCRINOLOGÍA", "ENDOSCOPIA", "EPIDEMIOLOGÍA", 
    "FARMACOLOGÍA", "GASTROENTEROLOGÍA", "GASTROENTEROLOGÍA PEDIÁTRICA", "GENÉTICA", "GERIATRÍA",
    "GERONTOLOGÍA", "GINECOLOGÍA", "GINECOLOGÍA OBSTETRICIA", "HEMATOLOGÍA", "HOMEOPATÍA", 
    "HOMEOPATIA", "IMAGENOLOGÍA DIAGNÓSTICA Y TERAPÉUTICA", "INFECTOLOGÍA", "INMUNOLOGÍA", 
    "MEDICINA CRÍTICA", "MEDICINA DE REHABILITACION", "MEDICINA DE URGENCIAS", "MEDICINA DEL DEPORTE", 
    "MEDICINA DEL TRABAJO Y AMBIENTAL", "MEDICINA ESTÉTICA", "MEDICINA FAMILIAR", "MEDICINA GENERAL", 
    "MEDICINA INTEGRADA", "MEDICINA INTENSIVA", "MEDICINA INTERNA", "MEDICINA LEGAL", 
    "MEDICINA NUCLEAR", "MEDICINA OCUPACIONAL", "NEFROLOGÍA", "NEONATOLOGÍA", "NEUMOLOGÍA", 
    "NEUROCIRUGÍA", "NEUROLOGÍA", "NUTRIOLOGÍA", "OBSTETRICIA", "OFTALMOLOGÍA", "ONCOLOGÍA",
    "ORTOPEDIA", "OTORRINOLARINGOLOGÍA", "OTRA", "PARASITOLOGÍA", "PATOLOGÍA", "PEDIATRÍA", 
    "PEDIATRÍA DERMATOLOGÍA", "PROCTOLOGÍA", "PSIQUIATRÍA", "RADIO ONCOLOGÍA", "RADIOLOGÍA", 
    "REHABILITACIÓN", "REUMATOLOGÍA", "SALUD PÚBLICA", "TERAPIA INTENSIVA", "TRAUMATOLOGÍA", "UROLOGÍA"
]